### ISSUE TITLE
hotspot3d search doesn't work

### ISSUE THREAD

**Issue by dwent** [ding-lab/hotspot3d#19]
I tried to run the hotspot3d as the README_demo.
cmd line:
hotspot3d search --maf-file */Demo/demo.maf --prep-dir*/Hotspot3D/ --3d-distance-cutoff 10 1>demo.search.out 2>demo.search.err
error:Could not open sites file
As the manu of hotspot3D, maf file and sites-file is required at least one. So I want to know why it dosesn't work.

**Comment by AdamDS** [comment]
Thank you for catching that. We will have a correction to this shortly.

**Comment by amilacsw** [comment]
This bug is now fixed in V1.7.2. Thank you for letting us know. Please feel
free to contact us if you have further questions.

**Comment by dwent** [comment]
Thanks for your reply! I will update to the latest version.

**Comment by dwent** [comment]
Hi, I have tried to use the V1.7.2, but it has a problem in the updating process.

First, I use the cmd line: git checkout v1.7.2
error: pathspec 'v1.7.2' did not match any file(s) known to git.

Second, the Hotspot3D v1.7.2 was download in the Hotspot directory and I update by using the cmd line：
sudo cpanm --reinstall HotSpot3D-1.7.2.tar.gz
The output is as fellows：
--> Working on HotSpot3D-1.7.2.tar.gz
Fetching file:///home/wtdai/hotspot3d/HotSpot3D-1.7.2.tar.gz ... OK

**gzip: stdin: not in gzip format
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
! Failed to unpack HotSpot3D-1.7.2.tar.gz: no directory
! Failed to fetch distribution** 

In addition, could you give me a demo site-file as the format example for reference?

**Comment by AdamDS** [comment]
@dwent,
Try `git pull origin master`, then `sudo cpanm HotSpot3D-1.7.2.tar.gz`.

**Comment by dwent** [comment]
@AdamDS 
Thanks for your reply！Now I installed Hotspot3D-1.7.2 rightly.
**cmd:sudo cpanm HotSpot3D-1.7.2.tar.gz**
--> Working on HotSpot3D-1.7.2.tar.gz
Fetching file:///home/wtdai/hotspot3d/HotSpot3D-1.7.2.tar.gz ... OK
Configuring HotSpot3D-1.7.2 ... OK
Building and testing HotSpot3D-1.7.2 ... OK
Successfully installed HotSpot3D-1.7.2
1 distribution installed

However,it still does not work.
**cmd：hotspot3d search --maf-file /home/wtdai/hotspot3d/Demo/demo.maf --prep-dir /mnt/hgfs/G/Tools/Structure/Hotspot3D/Prep_dir --3d-distance-cutoff 10**
echo：=====Parameters=====
 p-value-cutoff        = 1
 3d-distance-cutoff    = 10
 skip-silent           = 0
 missense-only         = 0
 linear-cutoff         = 0
====================
=====Data===========
 prep-dir              = /mnt/hgfs/G/Tools/Structure/Hotspot3D/Prep_dir
 maf-file              = /home/wtdai/hotspot3d/Demo/demo.maf
 transcript-id-header  = transcript_name
 amino-acid-header     = amino_acid_change
 drugport-file         = 
 site-file             = 
 output-prefix         = 3D_Proximity
====================
**Could not open sites file**

I am sorry for for bothering you. Could you give me a demo site-file as the format example for reference?

**Comment by dwent** [comment]
@AdamDS 
Thanks for your reply！Now I installed Hotspot3D-1.7.2 rightly.
cmd:sudo cpanm HotSpot3D-1.7.2.tar.gz
--> Working on HotSpot3D-1.7.2.tar.gz
Fetching file:///home/wtdai/hotspot3d/HotSpot3D-1.7.2.tar.gz ... OK
**Configuring HotSpot3D-1.7.2 ... OK
Building and testing HotSpot3D-1.7.2 ... OK
Successfully installed HotSpot3D-1.7.2**
1 distribution installed

However,it still does not work.
cmd：hotspot3d search --maf-file /home/wtdai/hotspot3d/Demo/demo.maf --prep-dir /mnt/hgfs/G/Tools/Structure/Hotspot3D/Prep_dir --3d-distance-cutoff 10
echo：
=====Parameters=====
 p-value-cutoff        = 1
 3d-distance-cutoff    = 10
 skip-silent           = 0
 missense-only         = 0
 linear-cutoff         = 0
====================
=====Data===========
 prep-dir              = /mnt/hgfs/G/Tools/Structure/Hotspot3D/Prep_dir
 maf-file              = /home/wtdai/hotspot3d/Demo/demo.maf
 transcript-id-header  = transcript_name
 amino-acid-header     = amino_acid_change
 drugport-file         = 
 site-file             = 
 output-prefix         = 3D_Proximity
====================
**Could not open sites file**


I am sorry for for bothering you. Could you give me a demo site-file as the format example for reference?

**Comment by AdamDS** [comment]
@dwent, you're not bothersome at all. The command you're trying should work without the site-file, and from our testing, we seem to have corrected the problem. To be sure though, I'd like to know more about the version you're seeing from a couple of checks.
When you run just `hotspot3d`, what version does it show? 
Also, can you respond with the output from `grep "sub getSite" ~wtdai/perl5/lib/perl5/lib/TGI/Mutpro/Main/Proximity.pm -n5` (I'm assuming your installation went to your $HOME/perl5/lib/perl5/ directory, where $HOME would be ~wtdai...otherwise, replace ~wtdai/perl5/lib/perl5/ with the path to your hotspot3d directory where you cloned/pulled the 1.7.2 version).

**Comment by dwent** [comment]
@AdamDS 
Thanks for your understanding and reply. Please forgive my reply not timely because of a business trip.

1.hostspot3d version
wtdai@ubuntu:~/hotspot3d$ hotspot3d 
Program: hotspot3d - 3D mutation proximity analysis program.
Version: V1.7.1
 Author: Beifang Niu, Adam D Scott, Sohini Sengupta, John Wallis & Amila Weerasinghe

The version is strange. I would delete the folder and reinstall it completely again. Do you think it is a good idea?

2.The other information is as bellow：
560-	}
561-	$fh->close();
562-	return \%transHash;
563-}
564-
565:sub getSites {
566-	my ( $this , $trans_to_uniprot ) = @_;
567-	my $sites = {};
568-	if ( defined $this->siteListFile() ) {
569-		my $fh = new FileHandle;
570-		unless( $fh->open( $this->siteListFile() ) ) {

**Comment by AdamDS** [comment]
By using sudo it is likely installing to a different directory (/usr/local/bin/hotspot3d or /Library/Perl/5.#/TGI/, depending on Linux or Mac). If you've followed our instructions in the README, the install should go to ~/perl5/bin/hotspot3d & ~/perl5/lib/perl5/TGI/. To fix your installation, I think if you just install without sudo, then it should work itself out. You can do a quick check with `which hotspot3d`, before and after this non-sudo installation. Let me know if that works.

**Comment by dwent** [comment]
@AdamDS 
Thanks for your reply!

wtdai@ubuntu:~$ which hotspot3d
/home/wtdai/perl5/bin//hotspot3d

**Comment by AdamDS** [comment]
@dwent 
Does it work now? If not, I can think of a few options for you to try out.
1) Run `cpanm HotSpot3D-1.7.2.tar.gz --reinstall`. Then run `hotspot3d` to check the version. 
2) Run `git pull origin master` from the head directory of your cloned repo. Report back with the output from that. Then run `git status` and report back with the output from that.
3) Delete your local cloned repo. Clone this repo and install again (you may need to delete the contents under `~/perl5/lib/perl5/TGI/Mutpro/` and `~/perl5/bin/hotspot3d`).

**Comment by dwent** [comment]
@AdamDS 
Thank you very much for your patience reply.
According to your recommendation option 3：
3. Delete your local cloned repo. Clone this repo and install again (you may need to delete the contents under ~/perl5/lib/perl5/TGI/Mutpro/ and ~/perl5/bin/hotspot3d).
The hotspot3d --search could run in demo file as described in README_demo.
The hotspot3d is a very useful computational  tool. But I would like to thank you for your patient and meticulous help again.

**Comment by AdamDS** [comment]
@dwent, thank you for the update. I'm glad you are able to use the tool now. Let us know if you run into any other issues.
I'll close this issue, since it sounds as though we resolved the initial problem.
